USE astroCollective;

#YYYY-MM-DD

INSERT INTO astronauts (astronaut_name, astronaut_photo, date_of_birth, date_of_death, country, hours_in_space, astronaut_profile)
VALUES ('John H. Glenn Jr.', 'https://www.nmspacemuseum.org/wp-content/uploads/2019/03/john-glenn-scaled.jpg', '1921-07-18', '2016-12-08', 'United States', 240.8, 'test'),
       ('Sally Ride', 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/Sally_Ride_%281984%29.jpg/1200px-Sally_Ride_%281984%29.jpg', '1951-05-26', '2012-07-23', 'United States', 343.8, 'profile for astronauts'),
       ('Ronald E. McNair', 'https://www.csus.edu/academic-affairs/mcnair-scholars-program/_internal/_images/ronald_mcnair.jpg', '1950-10-21', '1986-01-28', 'United States', 191.3, 'test test test'),
       ('Francis R. (Dick) Scobee', 'https://upload.wikimedia.org/wikipedia/commons/4/42/Scobee-fr.jpg', '1939-05-19', '1986-01-28', 'United States', 167.7, 'testing profile info'),
       ('L. Gordon Cooper Jr.', 'https://www.nasa.gov/wp-content/uploads/2023/05/l-gordon-cooper-jwfull.jpg', '1927-03-06', '2004-10-04', 'United States', 225.2, 'lorem ipsum lorem ipsum');

INSERT INTO missions (mission_name, launch_date, return_date, launch_location, space_agency, spacecraft, mission_insignia, mission_details)
VALUES ('STS-128', '2009-08-29', '2009-09-12', 'Kennedy Space Center, LC-39A', 'NASA', 'Space Shuttle Disovery', 'https://upload.wikimedia.org/wikipedia/commons/9/91/STS-128_insignia.jpg', 'STS-128 was a NASA Space Shuttle mission to the International Space Station that launched on August 28, 2009. Space Shuttle Discovery carried the Multi-Purpose Logistics Module Leonardo as its primary payload. Leonardo contained a collection of experiments for studying the physics and chemistry of microgravity.'),
       ('Apollo 13', '1970-04-11', '1970-04-17', 'Kennedy Space Center, LC-39A', 'NASA', 'Saturn V', 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/Apollo_13-insignia.png/1022px-Apollo_13-insignia.png', 'Apollo 13 was the seventh crewed mission in the Apollo space program and the third meant to land on the Moon. The craft was launched from Kennedy Space Center on April 11, 1970, but the lunar landing was aborted after an oxygen tank in the service module (SM) ruptured two days into the mission, disabling its electrical and life-support system.'),
       ('Gemini 8', '1966-03-16', '1966-03-17', 'Cape Kennedy LC-19', 'NASA', 'Titan II GLV', 'https://www.thespacecollective.com/media/catalog/product/cache/64b2ce5e9db1d173cc7981641bc9f2ca/image/232132c/gemini-8-patch.jpg', 'Gemini 8 was the sixth crewed spaceflight in the Gemini program. It was launched on March 16, 1966, and was the 14th crewed American flight and the 22nd crewed spaceflight overall. The mission conducted the first docking of two spacecraft in orbit, but also suffered the first critical in-space system failure of a U.S. spacecraft which threatened the lives of the astronauts and required an immediate abort of the mission. The crew returned to Earth safely.'),
       ('Apollo 8', '1968-12-21', '1968-12-27', 'Kennedy Space Center, LC-39A', 'NASA', 'Saturn V', 'https://upload.wikimedia.org/wikipedia/commons/f/fb/Apollo-8-patch.jpg', 'Apollo 8 was the first crewed spacecraft to leave low Earth orbit and the first human spaceflight to reach the Moon. The crew orbited the Moon ten times without landing, and then departed safely back to Earth.'),
       ('STS-37', '1991-04-05', '1991-04-11', 'Kennedy Space Center, LC-39B', 'NASA', 'Space Shuttle Atlantis', 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Sts-37-patch.png/2043px-Sts-37-patch.png', 'STS-37, the thirty-ninth NASA Space Shuttle mission and the eighth flight of the Space Shuttle Atlantis, was a six-day mission with the primary objective of launching the Compton Gamma Ray Observatory (CGRO), the second of the Great Observatories program which included the visible-spectrum Hubble Space Telescope (HST), the Chandra X-ray Observatory (CXO) and the infrared Spitzer Space Telescope.');

INSERT INTO rockets (rocket_name, rocket_status, rocket_launches, rocket_photo, rocket_details)
VALUES ('Saturn V', 'Retired', 12, 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Apollo_11_Launch_-_GPN-2000-000630.jpg/440px-Apollo_11_Launch_-_GPN-2000-000630.jpg', 'Saturn V is a retired American super heavy-lift launch vehicle developed by NASA under the Apollo program for human exploration of the Moon. The rocket was human-rated, had three stages, and was powered with liquid fuel. Flown from 1967 to 1973, it was used for nine crewed flights to the Moon, and to launch Skylab, the first American space station.'),
       ('Space Shuttle Challenger', 'Destroyed', 10, 'https://www.history.navy.mil/content/history/museums/nmusn/explore/photography/humanitarian/20th-century/1980-1989/1986-space-shuttle-challenger/_jcr_content/body/media_asset_248703872/image.img.jpg/1677782108795.jpg', 'Space Shuttle Challenger (OV-099) was a Space Shuttle orbiter manufactured by Rockwell International and operated by NASA. Named after the commanding ship of a nineteenth-century scientific expedition that traveled the world, Challenger was the second Space Shuttle orbiter to fly into space after Columbia, and launched on its maiden flight in April 1983. It was destroyed in January 1986 soon after launch in an accident that killed all seven crewmembers aboard.'),
       ('Space Launch System', 'Active', 1, 'https://aviationweek.com/sites/default/files/styles/crop_freeform/public/2022-08/slsprelaunch.jpg?itok=ToV9f2Lr', 'The Space Launch System (SLS) is an American super heavy-lift expendable launch vehicle used by NASA. As the primary launch vehicle of the Artemis Moon landing program, SLS is designed to launch the crewed Orion spacecraft on a trans-lunar trajectory. The first SLS launch was the uncrewed Artemis 1, which took place on 16 November 2022.'),
       ('Space Shuttle Endeavour', 'Retired', 25, 'https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2010/02/space_shuttle_endeavour_on_the_launch_pad/9274093-5-eng-GB/Space_Shuttle_Endeavour_on_the_launch_pad_pillars.jpg', 'Space Shuttle Endeavour (Orbiter Vehicle Designation: OV-105) is a retired orbiter from the Space Shuttle program and the fifth and final operational Shuttle built. It embarked on its first mission, STS-49, in May 1992 and its 25th and final mission, STS-134, in May 2011. STS-134 was expected to be the final mission of the Space Shuttle program, but with the authorization of STS-135 by the United States Congress, Atlantis became the last shuttle to fly.'),
       ('Mercury-Redstone Launch Vehicle', 'Retired', 6, 'https://upload.wikimedia.org/wikipedia/commons/8/88/Ham_Launch_-_GPN-2000-001007.jpg', 'The Mercury-Redstone Launch Vehicle, designed for Project Mercury, was the first American crewed space booster. It was used for six sub-orbital Mercury flights from 1960-1961; culminating with the launch of the first, and 11 weeks later, the second American (and the second and third humans) in space. The four subsequent Mercury human spaceflights used the more powerful Atlas booster to enter low Earth orbit.');